apiVersion: concourse.govsvc.uk/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: deploy
spec:
  exposed: true
  config:

    github_source: &github_source
      uri: https://github.com/alphagov/verify-proxy-node.git
      organization: alphagov
      owner: alphagov
      repository: verify-proxy-node
      github_api_token: ((github.api-token))
      access_token: ((github.api-token))
      approvers: ((trusted-developers.github-accounts))
      required_approval_count: 2

    task_toolbox: &task_toolbox
      type: docker-image
      source:
        repository: ((concourse.task-toolbox-image))
        tag: ((concourse.task-toolbox-tag))

    resource_types:

    - name: github
      type: registry-image
      source:
        repository: ((concourse.github-resource-image))
        tag: ((concourse.github-resource-tag))

    resources:

    - name: release
      type: github-release
      icon: tag
      source:
        <<: *github_source
        tag_filter: ^v1\.\d+$

    - name: daily
      type: time
      icon: update
      source:
        interval: 12h
        start: 8:00 AM
        stop: 8:00 PM

    jobs:

    - name: deploy-nl-integration
      serial: true
      plan:

      - get: release
        trigger: true

      - get: daily
        trigger: true

      - task: render-manifests
        config:
          platform: linux
          image_resource: *task_toolbox
          inputs:
          - name: release
          outputs:
          - name: manifests
          params:
            CLUSTER_NAME: ((cluster.name))
            CLUSTER_DOMAIN: ((cluster.domain))
            CLUSTER_PUBLIC_KEY: ((artefact-signing-key.publicKey))
            RELEASE_NAMESPACE: ((namespace-deployer.namespace))
            RELEASE_NAME: nl-integration
            CONNECTOR_NODE_NATIONALITY_CODE: NL
            CONNECTOR_ENTITY_ID: https://acc-eidas.minez.nl/EidasNodeC/ConnectorMetadata
            CONNECTOR_METADATA_FQDN: acc-eidas.minez.nl
            CONNECTOR_METADATA_PATH: /EidasNodeC/ConnectorMetadata
            CONNECTOR_METADATA_SIGNING_TRUSTSTORE_BASE64: MIIWbgIBAzCCFicGCSqGSIb3DQEHAaCCFhgEghYUMIIWEDCCFgwGCSqGSIb3DQEHBqCCFf0wghX5AgEAMIIV8gYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQU1+BLjtq6cFIYX+8SNsMJodZP5xsCAwDDUICCFbhdhc/XSVDzUO2Bbiyk3Lf9CfmgDXCVjLtOkP0oUOp7/iHkXU9nsEcxgyZrsB0+BP8jRvwk5svMaWxQKJjlWf0d0VsgBVRYyFmvCA2MA0FMR0Z3E0FSzeX5dPZ0Pyu0En0dgpEmvf+7T1ArMzuUeDWp/8uo1tuGf1VWQU4Os0SS+fsMa3wmf7803AC6Xrxg0edImP45LQPgTCFIToETciKEEPS9Ps29r6JIyEu4bK4AOkcKrxHhoXDN37feMYin0iocQufSLTlFocwWBoUnl+HEI4JI8UQs3pbWPEj4E/HQcuGL8NHfH3pjdTB4O3g5qFn80WFmKkLcgCGmu8TeI6/s1fY7lmds2xd+rgSciqr7/dpOVnHRmgFihlPt1RQOZimFTPDVA+oe6LzHEZO03lZjzlY1J/BkGngf3+sY+WqidTJ+cjj4IxKyxK/L0v6lOhs0QmKbafLdLjzNTNwhCX9cvlRIo/Vf4ZuRxomlqmSzYZnn7aMda7QQq5Z4c1rOM4iubOkD2FRjSmtD+xOceWYbe3iSJvjIEFqwL9HMf7XrK/wxFAvJ6HbxwUF56jy1nKIyTibYXYm5D/akAmEtVI0q/wNorB00T53efoql3mN5s2eZ9Z3fOGffOo3wLgLmi2AyscZ9o1gq4DgIwOl9eWchAk845b9XpB2joZjqX8SHbK+WBMK730tjQs1M7x9DtYr7+48/8NOBPCJqJXsIq3Nxj+JBdGqzDBWXkJ6pTX8vqGBRdr5bVncxFMLMAS5ao6OypLMw9UKy5DXozwSWNRgADIGsX460mlI/nCUBrAOQq6X2vKkcPIULroljxNO7o2aJuoQWjbnerxVAxV1ngI5sQ1QDERVbtInPdSvNePD8zUw1Cf2t2y77SedCvfOT1qvQJQXpkivsuHV0bvnRY8MIf/fazoB1hzwEMNaFheXges4EOrG5khmhKhZLhFeXQxh6EapVwLHx4SNao0rgOViCvkkZ+enk5u1oQ+9RrfqzaBxCSWc3bnsPMnGCPXsFqXiJPoBBX/r4nGzPyJabz33EWBOMOzgxVHmlafZMPOVBToHIiRESLBTZaThhp8oWviEhdnDiDn05SxwEj1q5cuQTux54myfzIbWgyUFxmZOkycPn/mtv76bJ5Qv3+R6IEJXfM9mf7UdEVoo1/QteLVFi0rmQMPDbOYaZPfLXu8ZQN4CoXZAe2SBwt7oecTZRhvc4Fa5nhAcVtTfNp6afG3NKv2UJPJtL9TBH54FA9jKHYHTjQVcLHYtIHUElkQK4bbNllJfbDd6gKDH915fstugHwBpGJBxkaCvkFfOnDDSq9VZL7fKXvbgYcztsHWQLtgOw2serC/MDbM2iuqTVCPI3LAYj5Wb/t0vd117SVWONDeLggfA0aC9h03QBxzmO0hyPL3RgMew0YR+mpE72MmoHL7tmOYCt453ePYZsuzDAgKSg+dSwmwakaw3tkFLOg02skXnqS64k6gzQCB8Fl9Ye5cbpNySs9J0c6PFOVC+5CwIcdGjjN68LfdBQ2hQLeGFidXChZh3JhuZ4IDFCyyEbBdLvkSeGVv+Ga67F/XQ+scW0NIlC5cc7ZUMFLlBCxXtbc+hXxEiOqvpMMawdsBUo2hVysTI5EKjaTjD5gLtkAcDNO00ISscOeMeJ1X2pRHWxdF/xK1dLxAr7XrGMw8SKle7z89HB4vc83dJx7BkSjGDiIvl+oYdpXSFQbg89IXlNQ4e07+n1JrxDvJJRl4yTQqDG0Jt8kCFWRf0Zi9qbC7I0sQy8NpVXsatoIyHE6C/0O9KMbiAV5uzZcGzQwE+ExJSblmS2Q8KrTeEewY8xzhgDqjJClgsXjyPuDe7Gz3B1RgLURjy7ehx8ZsspRHhcy2tYmFuaNulKvQRtshwQOuaGIiEpC9JOAHlVzt1v4TnlIJBfEcY6e5eDhKWtJGmpsJI3QXnKoQp8DkGm7fv3sy7u79eEfeILB42MkfmQnygcU4do5Nng+N5gQajOtl488NaJt3l8SklDR25HZHoyxQnfVw+Pw25fzm6qf4Sk4cNM6yKo9jmnjrgtUrkrzHK6iT8hZ5d37CuPnT5sWiNdTVKeRo7cw4duBW1gBnCTUdx7yDt8lZuuXUDOa/mVsvF7ifOi9tter2sjFirzrv8N478V4UpGE6rMmxQPb5xAJELFNvLfDVq3ANoG0Ax6oSFvtdnbiN+q4nNq6RjjWLt0EKoBb6gGZY2h4Y77csenqQ510F/byhPQOJC35/kcV+Hfa09pZObaI6Tk8Ci/a0vhuwD+I920M0pIquG5QG/sEjlD4NdRL3NJB73QFyhzs/UN3sXzI6RC0QgHmMJ0w04YJTrgp+07kEJH5yGiO/K9lfjND62hGMRJXSXH3fFhL0xt4Uh56oP+S+MBUoHSLrvH9aDqyqymOa5SqWKg4AMBhefqRsQCUQAUuvLAO+oWuIMtkIKjX+SdAqhbR15jfjTFBbqN3+JOY1SgL0shWdCC9PbdNCWNFi64I/pvSZQ/4LzFQY3dS7cSQAFOZcMfGq1Z5YBcfV60N9lDONQ1reezyxBy/3VGXfzCeI8l/kVjCKQEWcYH9bIbzPI5SZ4qNLKja0709R166FKdTNGjMdUcOUUpmjzvv9L3rwx7MzR2CH/wo2HAxfQczvD4ROk0uzecSEKLBxbMwtAaQJNk8M+Llp93vV7OFRVNs/bdcqqAiLUEqSnr8IYGy6HttChd61IM2Pc1iyBHbRIVL0XSW94Jbgkj4qj1XQlm5qlahbhoJN/tjUGF1wMh1SM0PDqWSO6lSeolu086osjGN3ErRuoZYoTY8qHtEQrbX006WFYM7jGXbneNnk7G6Qq2/EimpXCP+3lEUy1USfTahDHoFwBS9Cfh10zi2FgPS4w/2NbN28cco+w7PyhomuHrfPNRGPrBFqkgbIjPjnEtGDZXw5DNsuVf8oYr+OZ+abz3L6spgr7+pHUpwkE3NFYK4nl/BSof6bs9GP4Poa5yPMaMy7VxT4I2vf7h1H/VWZnxfwHm69c/DhVBGIzy6b5k4W/XmQW5qvgyz8ttGD7wVtBeJ+Twer4sgd6rcf23Znra1AnFU7Jgg3rcdOp1f7lwtjy/ZhmoR7uTuq/miKXooXY659UAHpSAvc2spgb1hL/alO2gW+2mBLX3VQeheMLFnKHS5+OimiQrx7vM2jHOeMOjnrsBAeDLNzcLzv2QOWn35xBSlfV7cvB/z6auRPj30tBdv+iivpVft6kNTaF8BPFR6WAqbYUmCMdhQkdA3kJBpQwz3cQcSp/R18PU4gX/vESzQ76tDJPPV97jEqBn7JaLSKGwpStx0AZSDyvQG27loQ/oD1qUUwUkF7WgT5FgPpqiHpC0Oz39TFSjpOvu3aTproVZIy3fKFQI9tOb13OJxxEA8KxvkoWf9tfmPuEkpRAnY4g9l++GWsUokudBq/UXgj380GclgsKDCNYXMydjYPWqoyWSDw6JdHrEPzrskdq67IUwDndSaPv1Ng8CzxazhOtUjw2w/amDFXjk6OLlaiEFr+cTSm8lFMo4fsTHcztBezKNF0Pfrbx+sXq0YoQKBIsydAE8COPP3ldGSiQkGIlQ64z213sE/6OiJ48cxPgKMh69y5AJLo7seqLXzEWl/9wDWBAGCECvr1XB5CXcvt+AmyMwCSNUwCcTuLtn6tD444K5HEyYLNnd5XQc8YgKXWb0tNDRSFgCVjINfn1ooc7UnNukRdc3qzrYrz1AzKExMMJahHD9TUpg5GbokDYhWXdcjDeF8RnFEGYLk2dmX1rOcVefoCUjlwoGgll5whiJbsONDbdGeDcWEvuyXIEshggWEqkQME4tfJpIvSk8gEviEVqQxJPetntmc3R6p/UVLjUH08CYfhvkBw4gdBBx5HfqIwz6WXbSGDPMGcFMqp5bcQoUf1Xm9rAJregB1mF9Do5B/jkpQxYHQRlnq8CTrsPhe+M3v4gA10bajYw6I9rPtQs1W69eBad7PC6EVzfz0TUHaSTMWnqjo28xQ61HFl2dkj2+F1nmti1eJ1TSqLNZTlRs2SsrRTyPpYYUvLmbWLEvJD2s7g5gO/NTSEVdt/0L624rDpKT69/1zdj4p5xVdNZRk8k1rz5D+lRoyf2tamKwkaDm7C34jijVQ/eb8yiqL1AVcrbNfHKPNm8BLOR7QYECeVjnKZzJ8W1ej/0Vuyd0aWXM1Dc4UFHZhwv7NQd+LGT6lXnYRpSMNfCNz+C0tJKFbDIOTaakdyb8qHz8IVkQglqozAOxp8LgnFcXlq5TBxzi5A5oG3y/SV7CIYzwYVvxyvFE7c9kA8x98sbOe6cnf9JaErowC3ofkzInzngIAboECNpTiCmz1iH1fwPfPJSBIeXwVbnLnBytpOrhQ5vmGWECwVc3LnKtj2Y1s97d183A9uKGXI0KfOYa5rBaH9ytEQeJCRRWi8SvayPqcFtcwxp7e3HvzplOrnDNYDMU+hmNGPKx2BoVwcfdWWFMXyj5TzBJ2eu9qpoal05jrgTrvll6EmO8E9Ed+UwN6EdPwKcNRjGLs/0FK2r0sEfJa/higZB5O0e8B/oJVVtY+IBf8BogVug1HoDIE2MEc445TiQJYFOjjP6uaiVTBNKgWBjcFvcAO2u/WHtplZHpo7RvrTSREVXGyXxNxAlqi73saWxk3uf3WmVfB/YoTVtrkfczUgjUL4P5VZbbsgmdpnPVeDqKJmtz9M/ne+LiIPVk23CzqmNKb61ik6SbWYeXdDft43JvHyecb0lUozEoAPwi/buXjP6gRMfIe2m1xy8q+DOzRwMmca8VRK7QOZIC7jdtLLk2BcmW8obIDMhD5XZ51yuxlNO+PdW1+7fYewZpIwhb0ZJC6iMGZRrztU40a8Exxy2fXop+p1jCbQpB7bG5asnmD12DyvQginPdzXeQ0r6MQe/8OahwiNmgh9g7W+C68whpl4DChp8e4/5L1L3LR8XiLNWJfvN4T3qNMJ0+jdusm86Hgj5OaaqacfrEjqkrPNS02meddhOvrAgrMQDRjtgJXrKcvoCmSXtYGZUbTbuLHasamopNZOc4Jh4Sg2K0KOyeR+pJMJoOIn4UoKTdgOHeCWW9zzgD09pUW5fb3lDnsvhufAeuCIJ5u891Aen/Jm6NE7Z0OPwUfJffWnS2iKD4muaqpabj8h/RYbkqEpMT1HflqOtNdpkC8z+P5YQDlnlUdy92MaV7EA5UejeHROflAOwohqjubI/p7rT5IMRw1yY68Jyj71bdOEaD1zyuvfC1ieWW+HZUlDyIbXAmJurk6OtCNHm7CGI6z5fRjaCaA/k922TCKCVC2EPRdoMJ9+1xgYQvZ6ac5ypsyJ0WCz1ovYJR6yQWZZZDZwBUqZRJ12HPO/WxVSmJToMWe2mMAiXwrbrOUuQ2K4x9nzIjFX++bMPejXlT9h9Rfz6CwqV5aQOx7qS+ButDfUAVWGDgJyHzGO8KSm0geeQSTccwHYQRWW9JDJhhDFi7ffc+MnWvgefGTgu1hx1+qCyBmvxYdBco16brX4Eq0Gymtj3kAFdrCiYrQWwN8SnNVT5JJLDYG40bWry7BT+PBdLL91EgcD0Y3g9emm7sdgynz8DMe9Q5Q0hAWN/aEevmHaxSDzHPYN0eWafZMQ7LpLmU8wB5zhEeH1tWsuAluiuc2QewpgCtiRjAQ0UW5dOKm1LDB+AgvC0NT1LTuzDtGGn4D45zBR/a69EcUq9BCNmlgH5gLtSdG4Rt1GJLxu0ItoIWU/Ktff/HgZBFiatzlrpiagDDo0TepnpPUCuWYm3AkHe2H39WytuQcK31cOJ2why2G9Q8IKW6S8Xab8tWSIj8p87RLFP0K14OhyVt9LA0bh25vA8cFYgfFlVuW/KN/QGWrhujnRIzcWJ3tXz1x7SHZ1sH/Ts+2DAdzqgM5Kagobzuv9JuIrkwsI0ZXbWOOrwrl3a4Wcsh5FT9iwqPLHDodVeiAU1fi4q/TN8sOpGKYBRuXDOX7lRuMiBxwR+shd/LbjZU/6MSnj4XA4vFZxJBuPeKR3dvkZz0YLhYL8gNRvKSRpAYH7k4i63FyTq3JhUKtcxWPrFY5Ucgbt+Ns4DFm35f1LsadLcYp837rs1Wmd4UAUrJHJkhdXGG7yZpte6TW9jmsYXw39lPOeTAFQs6dJYF3E+FEBwtBr7qNfKfd6JSL/Y9i90tjhOQsArx13ZIUfo83I1fFRAWHX2JW+xwKCfiKF/ME+J6U7hdc4YT2Tpg01e/+aPVXY7nO8LBVzI3duigAijmQRd3NMasUiDcBPjRllHYSMh/etAlfOflwp/Kgu+g44h+bk2DVh04LbcX0ImqOvzdCTKEMchEH20/fIT826Kbc66vrzbwCfaT6hy64CdaGwPG0CFWVkFvCpmos0+gUt2FU0D6HkdlfsmaOtCPWbHkYtNGWuw7xBJ/nh0WASpZpHN6YxCm6PHGQQgIS34OKSyoldzHjInwNcdOkG/O8sbp3lyp6KRWMAzvmmD0XnsXX4qy0+mAyt/YwUGU9hDuTnF5Fyos8NnHUDGd5GGdCwCHBW3lFWAgY23prCdHDtPckr14Bov9/ATgHr5T1pKrIcvao+nMsAfKbjQjIo/ttWt8caJvvgxuaNwMNoA0Ik/XLq3Pb0O2BH2RiMpykf5luNzXLxWSwxmMJkJAS9efyLdkkf0r0R13/U3E2vP6bCp+G7NNW6t1iWTOpK+YJ6YTGJdUC+P9kFi8+JvG3W5V+GvCJ8EKCdaRTgok2nfoiEpqZYqNubHMtJR1+5n1Usq37ia+W8vVzFcuzBu+R6k3QEROaVHl5p6PqDv5rMQrTkUqWzsHI2jyMJmrFsW7i3Z1fyuN6e7J478i2Gly1vLOURerSN7eLx9KvhVpOv6JdqxbPZnQIkd+C5r6lxPyyViSJVLVaIf+5OvA5HCAP4loJQKY8inh9WQj+419git74Kz1NcqR3XNy/BzoyLvuorRE885078Kks5FdMWI3QF3JnDUA86cxsq2PGiHZSz8YVSdy1XxZHObkfWR+Wt9ufjW0NUYOI4K2pKOGOW7JHbxhBw2lk0V/Z4TXcoIBqy21XjeIt7q5DRENN5qWzgLNCkcOGowt1NxB8ytLJwy709EAhfQqK+xOZee/dGxXAYGNjyjEy1hmr8jffgWPOadLRh7+vXLd+aINSIQGXnmaGrMoRiaYMwQ8rtB6NCW1bfUZnYkELGKXph0H8Ks/g4rI7bx85pQ4IXb9zdolMKmxKaKGw9HDP5x94ryynQPJubQJe9caFFE3Fbsn6NDypvDE0C7aUTw7fAbksdUUlqTGXI5S+11vE5qxJwKLxbpixqDJEd79XeXEjfEjiXLByqZHL9VOV8lgnmAFB+QTCZwsuNPlqpkEjefZ3iQlMunPucuy0qG0KbansfXAMD4wITAJBgUrDgMCGgUABBQBZNmQAXtRPocCHmotAAQSpqkO7QQUkANxv5/WBQIWAR/qIO89RT3XDXECAwGGoA==
            CLOUDHSM_IP: ((cluster.cloudHsmIp))
          run:
            path: /bin/bash
            args:
            - -euc
            - |
              echo "preparing keyring..."
              echo "${CLUSTER_PUBLIC_KEY}" > key
              gpg --import key
              gpg --export > ~/.gnupg/pubring.gpg
              echo "verifying package"
              helm verify ./release/*.tgz
              echo "rendering chart with release name '${RELEASE_NAME}' and namespace '${RELEASE_NAMESPACE}'..."
              helm template \
                --name "${RELEASE_NAME}" \
                --namespace "${RELEASE_NAMESPACE}" \
                --set "global.cluster.name=${CLUSTER_NAME}" \
                --set "global.cluster.domain=${CLUSTER_DOMAIN}" \
                --set "global.cloudHsm.ip=${CLOUDHSM_IP}" \
                --set "connector.entityID=${CONNECTOR_ENTITY_ID}" \
                --set "connector.metadata.fqdn=${CONNECTOR_METADATA_FQDN}" \
                --set "connector.metadata.path=${CONNECTOR_METADATA_PATH}" \
                --set "connector.metadataSigningTruststoreBase64=${CONNECTOR_METADATA_SIGNING_TRUSTSTORE_BASE64}" \
                --set "translator.connectorNodeNationalityCode=${CONNECTOR_NODE_NATIONALITY_CODE}" \
                --output-dir "./manifests/" \
                ./release/*.tgz

      - task: deploy-manifests
        timeout: 10m
        config:
          platform: linux
          image_resource: *task_toolbox
          inputs:
          - name: manifests
          params:
            KUBERNETES_SERVICE_ACCOUNT: ((namespace-deployer))
            KUBERNETES_TOKEN: ((namespace-deployer.token))
            KUBERNETES_API: kubernetes.default.svc
            RELEASE_NAMESPACE: ((namespace-deployer.namespace))
            RELEASE_NAME: nl-integration
            APP_NAME: proxy-node
          run:
            path: /bin/bash
            args:
            - -euc
            - |
              echo "configuring kubectl"
              echo "${KUBERNETES_SERVICE_ACCOUNT}" | jq -r .["ca.crt"] > ca.crt
              kubectl config set-cluster self --server=https://kubernetes.default --certificate-authority=ca.crt
              kubectl config set-credentials deployer --token "${KUBERNETES_TOKEN}"
              kubectl config set-context deployer --user deployer --cluster self
              kubectl config use-context deployer

              echo "applying chart to ${RELEASE_NAMESPACE} namespace..."
              kapp deploy \
                -y \
                --namespace "${RELEASE_NAMESPACE}" \
                --allow-ns "${RELEASE_NAMESPACE}" \
                --app "${RELEASE_NAME}-${APP_NAME}" \
                --diff-changes \
                -f ./manifests/

    - name: deploy-test-integration
      serial: true
      plan:

        - get: release
          trigger: true

        - get: daily
          trigger: true

        - task: render-manifests
          config:
            platform: linux
            image_resource: *task_toolbox
            inputs:
              - name: release
            outputs:
              - name: manifests
            params:
              CLUSTER_NAME: ((cluster.name))
              CLUSTER_DOMAIN: ((cluster.domain))
              CLUSTER_PUBLIC_KEY: ((artefact-signing-key.publicKey))
              RELEASE_NAMESPACE: ((namespace-deployer.namespace))
              RELEASE_NAME: test-integration
              CLOUDHSM_IP: ((cluster.cloudHsmIp))
            run:
              path: /bin/bash
              args:
                - -euc
                - |
                  echo "preparing keyring..."
                  echo "${CLUSTER_PUBLIC_KEY}" > key
                  gpg --import key
                  gpg --export > ~/.gnupg/pubring.gpg
                  echo "verifying package"
                  helm verify ./release/*.tgz
                  echo "rendering chart with release name '${RELEASE_NAME}' and namespace '${RELEASE_NAMESPACE}'..."
                  helm template \
                    --name "${RELEASE_NAME}" \
                    --namespace "${RELEASE_NAMESPACE}" \
                    --set "global.cluster.name=${CLUSTER_NAME}" \
                    --set "global.cluster.domain=${CLUSTER_DOMAIN}" \
                    --set "global.cloudHsm.ip=${CLOUDHSM_IP}" \
                    --set "stubConnector.enabled=true" \
                    --output-dir "./manifests/" \
                    ./release/*.tgz

        - task: deploy-manifests
          timeout: 10m
          config:
            platform: linux
            image_resource: *task_toolbox
            inputs:
              - name: manifests
            params:
              KUBERNETES_SERVICE_ACCOUNT: ((namespace-deployer))
              KUBERNETES_TOKEN: ((namespace-deployer.token))
              KUBERNETES_API: kubernetes.default.svc
              RELEASE_NAMESPACE: ((namespace-deployer.namespace))
              RELEASE_NAME: test-integration
              APP_NAME: proxy-node
            run:
              path: /bin/bash
              args:
                - -euc
                - |
                  echo "configuring kubectl"
                  echo "${KUBERNETES_SERVICE_ACCOUNT}" | jq -r .["ca.crt"] > ca.crt
                  kubectl config set-cluster self --server=https://kubernetes.default --certificate-authority=ca.crt
                  kubectl config set-credentials deployer --token "${KUBERNETES_TOKEN}"
                  kubectl config set-context deployer --user deployer --cluster self
                  kubectl config use-context deployer

                  echo "applying chart to ${RELEASE_NAMESPACE} namespace..."
                  kapp deploy \
                    -y \
                    --namespace "${RELEASE_NAMESPACE}" \
                    --allow-ns "${RELEASE_NAMESPACE}" \
                    --app "${RELEASE_NAME}-${APP_NAME}" \
                    --diff-changes \
                    -f ./manifests/
                  echo "deleting ${RELEASE_NAMESPACE} connector pod"
                  kubectl -n ${RELEASE_NAMESPACE} delete pod -l app.kubernetes.io/name=connector
