apiVersion: concourse.govsvc.uk/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: smoke-test
spec:
  exposed: true
  config:

    resources:

    - name: every-10m-9-5
      type: time
      source:
        interval: 10m
        start: 9:00 AM
        stop: 5:00 PM

    - name: tests-image
      type: registry-image
      icon: file-document
      source:
        username: ((pipeline.ImageRegistryUsername))
        password: ((pipeline.ImageRegistryPassword))
        repository: 367051407649.dkr.ecr.eu-west-2.amazonaws.com/verify-verify-proxy-node-build-tests
    jobs:

    - name: smoke-test-integration
      plan:

      - get: every-10m-9-5
        trigger: true
      - get: tests-image

      - task: test-chart-package
        image: tests-image
        attempts: 2
        timeout: 2m
        config:
          platform: linux
          params:
            PROXY_NODE_URL: "https://test-integration-proxy-node.((cluster.domain))"
            STUB_CONNECTOR_URL: "https://test-integration-connector.((cluster.domain))"
            STUB_IDP_USER: "stub-idp-demo-one"
            SELENIUM_HUB_URL: "https://selenium.tools.signin.service.gov.uk/wd/hub"
          run:
            path: /bin/bash
            args:
            - -euc
            - |
              cd /
              bundle exec cucumber features/smoke/integration.feature --strict --tags "not @ignore"
