version: '3.8'

networks:
  default:
    name: verify-proxy-node

services:
  proxy-node-gateway:
    image: eidas/proxy-node-gateway
    container_name: proxy-node-gateway
    build:
      context: .
      dockerfile: local-startup/Dockerfile
      args:
        component: proxy-node-gateway
        USE_LOCAL_BUILD: ${USE_LOCAL_BUILD:-true}
        VERIFY_USE_PUBLIC_BINARIES: ${VERIFY_USE_PUBLIC_BINARIES:-false}
    env_file: ./local-startup/docker.env
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6602"
    ports:
      - "6600:6600"
      - "6602:6602"
    volumes:
      - ./proxy-node-gateway/build/install/proxy-node-gateway:/app/local
      - ./local-startup/metadata:/app/metadata

  eidas-saml-parser:
    image: eidas/eidas-saml-parser
    container_name: eidas-saml-parser
    build:
      context: .
      dockerfile: local-startup/Dockerfile
      args:
        component: eidas-saml-parser
        USE_LOCAL_BUILD: ${USE_LOCAL_BUILD:-true}
        VERIFY_USE_PUBLIC_BINARIES: ${VERIFY_USE_PUBLIC_BINARIES:-false}
    env_file: ./local-startup/docker.env
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6002"
    ports:
      - "6000:6000"
      - "6002:6002"
    volumes:
      - ./eidas-saml-parser/build/install/eidas-saml-parser:/app/local
      - ./local-startup/metadata:/app/metadata

  translator:
    image: eidas/translator
    container_name: translator
    build:
      context: .
      dockerfile: local-startup/Dockerfile
      args:
        component: proxy-node-translator
        USE_LOCAL_BUILD: ${USE_LOCAL_BUILD:-true}
        VERIFY_USE_PUBLIC_BINARIES: ${VERIFY_USE_PUBLIC_BINARIES:-false}
    env_file: ./local-startup/docker.env
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6662"
    ports:
      - "6660:6660"
      - "6662:6662"
    volumes:
      - ./proxy-node-translator/build/install/proxy-node-translator:/app/local
      - ./local-startup/pki/verify-dev-pki:/app/verify-dev-pki
      - ./local-startup/pki/test:/app/pki

  stub-connector:
    image: eidas/stub-connector
    container_name: stub-connector
    build:
      context: .
      dockerfile: local-startup/Dockerfile
      args:
        component: stub-connector
        USE_LOCAL_BUILD: ${USE_LOCAL_BUILD:-true}
        VERIFY_USE_PUBLIC_BINARIES: ${VERIFY_USE_PUBLIC_BINARIES:-false}
    depends_on:
      - proxy-node-gateway
    env_file: ./local-startup/docker.env
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6612"
    ports:
      - "6610:6610"
      - "6611:6611"
      - "6612:6612"
    volumes:
      - ./stub-connector/build/install/stub-connector:/app/local
      - ./local-startup/pki/verify-dev-pki:/app/verify-dev-pki
      - ./local-startup/metadata:/app/metadata
      - ./local-startup/pki/test:/app/pki

  metatron:
    image: eidas/metatron
    container_name: metatron
    build:
      context: .
      dockerfile: local-startup/Dockerfile
      args:
        component: metatron
        USE_LOCAL_BUILD: ${USE_LOCAL_BUILD:-true}
        VERIFY_USE_PUBLIC_BINARIES: ${VERIFY_USE_PUBLIC_BINARIES:-false}
    depends_on:
      - stub-connector
    env_file: ./local-startup/docker.env
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6672"
    ports:
      - "6670:6670"
      - "6671:6671"
      - "6672:6672"
    volumes:
      - ./metatron/build/install/metatron:/app/local
      - ./local-startup/metadata:/app/metadata

  verify-service-provider:
    image: eidas/verify-service-provider
    container_name: verify-service-provider
    build:
      context: ../verify-service-provider
      dockerfile: ../verify-proxy-node/local-startup/vsp/Dockerfile
      args:
        USE_LOCAL_BUILD: ${USE_LOCAL_BUILD:-true}
        VERIFY_USE_PUBLIC_BINARIES: ${VERIFY_USE_PUBLIC_BINARIES:-false}
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:50402"
    command: ["development", "-p", "50400", "-u", "http://localhost:6600/SAML2/SSO/Response/POST"]
    ports:
      - "50400:50400"
      - "50402:50402"
    volumes:
      - ../verify-service-provider/build/install/verify-service-provider:/app/local

  verify-service-provider-local-hub:
    image: eidas/verify-service-provider-local-hub
    container_name: verify-service-provider-local-hub
    build:
      context: ../verify-service-provider
      dockerfile: ../verify-proxy-node/local-startup/vsp/Dockerfile
      args:
        LOCAL_HUB: "true"
        USE_LOCAL_BUILD: ${USE_LOCAL_BUILD:-true}
        VERIFY_USE_PUBLIC_BINARIES: ${VERIFY_USE_PUBLIC_BINARIES:-false}
    env_file: ./local-startup/docker.env
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:50402"
    networks:
      default:
        aliases: [verify-service-provider]
    ports:
      - "50400:50400"
      - "50402:50402"
    volumes:
      - ../verify-service-provider/build/install/verify-service-provider:/app/local
      - ./local-startup/vsp/hub-metadata.truststore:/app/hub-metadata.truststore
      - ./local-startup/vsp/verify-service-provider-local-hub.yml:/app/verify-service-provider-local-hub.yml
