apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Release.Name }}-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    externaldns.k8s.io/namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: {{ .Release.Namespace }}-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
{{- if .Values.global.qwacCertificate.enabled }}
    - {{ include "gateway.host.govuk" . }}
{{- else }}
    - {{ include "gateway.host" . }}
{{- end }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
{{- if .Values.global.qwacCertificate.enabled }}
    tls:
      mode: SIMPLE
      serverCertificate: sds
      privateKey: sds
      credentialName: gateway-ingress-certificate-for-signin-sealed-secret
    hosts:
    - {{ include "gateway.host.govuk" . }}
{{- else }}
    tls:
      mode: SIMPLE
      serverCertificate: sds
      privateKey: sds
      credentialName: {{ .Release.Name }}-gateway-ingress-certificate
    hosts:
    - {{ include "gateway.host" . }}
{{- end -}}
