apiVersion: verify.gov.uk/v1beta1
kind: CertificateRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ .Release.Name }}-proxy-node-metadata-signing-cert-a1
  namespace: {{ .Release.Namespace }}
spec:
  countryCode: GB
  commonName: Verify Proxy Node Metadata Signing
  expiryMonths: 9
  organization: Cabinet Office
  organizationUnit: GDS
  location: London
  CACert: false
  certificateAuthority:
    secretName: proxy-node-metadata-ca-a1
    namespace: {{ .Release.Namespace }}
