{{- if .Values.stubConnector.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}-connector-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-connector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  secretName: {{ .Release.Name }}-connector-ingress-certificate
  dnsNames:
  - sc.{{ .Release.Namespace }}.{{ .Values.global.cluster.domain }}
  - {{ include "stubConnector.host" . }}
  issuerRef:
    name: letsencrypt-r53
    kind: ClusterIssuer
{{- end -}}
