version: '3.8'

networks:
  default:
    name: proxy-node-acceptance-tests

services:
  selenium-hub:
    image: selenium/standalone-firefox
    container_name: selenium-hub
    ports:
      - "4444:4444"

  acceptance-tests:
    build: .
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
      - TEST_ENV
      - SHOW_BROWSER
      - BROWSER
    working_dir: /tests
    volumes:
    - .:/tests
