version: '3.4'

services:
  selenium-hub:
    image: selenium/standalone-firefox
    container_name: selenium-hub
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "4444:4444"

  acceptance-tests:
    build: .
    depends_on:
      - selenium-hub
    env_file: ./docker_local.env