---
apiVersion: concourse.govsvc.uk/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: deploy
spec:
  exposed: true
  config:

    github_source: &github_source
      uri: https://github.com/alphagov/verify-proxy-node.git
      organization: alphagov
      owner: alphagov
      repository: verify-proxy-node
      github_api_token: ((github.api-token))
      access_token: ((github.api-token))
      approvers: ((trusted-developers.github-accounts))
      required_approval_count: 2

    task_toolbox: &task_toolbox
      type: docker-image
      source:
        repository: ((concourse.task-toolbox-image))
        tag: ((concourse.task-toolbox-tag))

    openjdk_image: &openjdk_image
      type: docker-image
      source:
        repository: amazoncorretto
        tag: 11

    resource_types:

    - name: github
      type: registry-image
      source:
        repository: ((concourse.github-resource-image))
        tag: ((concourse.github-resource-tag))

    resources:

    - name: release
      type: github-release
      icon: tag
      source:
        <<: *github_source
        tag_filter: ^v2\.\d+$

    - name: daily
      type: time
      icon: update
      source:
        interval: 12h
        start: 8:00 AM
        stop: 8:00 PM

    - name: eidas-config-integration
      type: git
      source:
        uri: https://github.com/alphagov/verify-eidas-config.git
        branch: master
        paths: [integration]
        username: "re-autom8-ci"
        password: ((github.api-token))

    jobs:
    - name: deploy-integration
      serial: true
      plan:

        - get: release
          trigger: true

        - get: daily
          trigger: true

        - get: eidas-config-integration
          trigger: true

        - task: generate-eidas-config
          config:
            platform: linux
            image_resource: *openjdk_image
            inputs:
              - name: eidas-config-integration
            outputs:
              - name: eidas-config-integration
            run:
              dir: eidas-config/tools
              path: ./gradlew
              args:
                - run
                - --args
                - "generate-config --environment=integration"

        - task: create-eidas-config-map
          config:
            platform: linux
            image_resource: *task_toolbox
            inputs:
              - name: eidas-config-integration
            outputs:
              - name: manifests
            params:
              KUBERNETES_SERVICE_ACCOUNT: ((namespace-deployer))
              KUBERNETES_TOKEN: ((namespace-deployer.token))
              NAMESPACE: ((namespace-deployer.namespace))
            run:
              path: /bin/sh
              args:
                - -euc
                - |
                  cd eidas-config/tools

                  echo "configuring kubectl"
                  echo "${KUBERNETES_SERVICE_ACCOUNT}" | jq -r .["ca.crt"] > ca.crt
                  kubectl config set-cluster self --server=https://kubernetes.default --certificate-authority=ca.crt
                  kubectl config set-credentials deployer --token "${KUBERNETES_TOKEN}"
                  kubectl config set-context deployer --user deployer --cluster self
                  kubectl config use-context deployer

                  echo "generating configMap resource definition from file"
                  kubectl -n "${NAMESPACE}" create configmap integration-countries-config --from-file=countriesConfig.yaml -o yaml --dry-run \
                    | yq -y '.metadata += {"annotations": {"kapp.k14s.io/versioned": "", "kapp.k14s.io/num-versions":"5"}}' \
                    | tee ../../manifests/countriesConfigMap.yaml

        - task: render-manifests
          config:
            platform: linux
            image_resource: *task_toolbox
            inputs:
              - name: release
              - name: manifests
            outputs:
              - name: manifests
            params:
              CLUSTER_NAME: ((cluster.name))
              CLUSTER_DOMAIN: ((cluster.domain))
              CLUSTER_PUBLIC_KEY: ((artefact-signing-key.publicKey))
              RELEASE_NAMESPACE: ((namespace-deployer.namespace))
              RELEASE_NAME: integration
              CLOUDHSM_IP: ((cluster.cloudHsmIp))
            run:
              path: /bin/bash
              args:
                - -euc
                - |
                  echo "preparing keyring..."
                  echo "${CLUSTER_PUBLIC_KEY}" > key
                  gpg --import key
                  gpg --export > ~/.gnupg/pubring.gpg
                  echo "verifying package"
                  helm verify ./release/*.tgz
                  echo "rendering chart with release name '${RELEASE_NAME}' and namespace '${RELEASE_NAMESPACE}'..."
                  helm template \
                    --name "${RELEASE_NAME}" \
                    --namespace "${RELEASE_NAMESPACE}" \
                    --set "global.cluster.name=${CLUSTER_NAME}" \
                    --set "global.cluster.domain=${CLUSTER_DOMAIN}" \
                    --set "global.cloudHsm.ip=${CLOUDHSM_IP}" \
                    --set "stubConnector.enabled=true" \
                    --set "vsp.secretName=vsp-integration" \
                    --output-dir "./manifests/" \
                    ./release/*.tgz

        - task: deploy-manifests
          timeout: 10m
          config:
            platform: linux
            image_resource: *task_toolbox
            inputs:
              - name: manifests
            params:
              KUBERNETES_SERVICE_ACCOUNT: ((namespace-deployer))
              KUBERNETES_TOKEN: ((namespace-deployer.token))
              KUBERNETES_API: kubernetes.default.svc
              RELEASE_NAMESPACE: ((namespace-deployer.namespace))
              RELEASE_NAME: integration
              APP_NAME: proxy-node
            run:
              path: /bin/bash
              args:
                - -euc
                - |
                  echo "configuring kubectl"
                  echo "${KUBERNETES_SERVICE_ACCOUNT}" | jq -r .["ca.crt"] > ca.crt
                  kubectl config set-cluster self --server=https://kubernetes.default --certificate-authority=ca.crt
                  kubectl config set-credentials deployer --token "${KUBERNETES_TOKEN}"
                  kubectl config set-context deployer --user deployer --cluster self
                  kubectl config use-context deployer

                  echo "applying chart to ${RELEASE_NAMESPACE} namespace..."
                  kapp deploy \
                    -y \
                    --namespace "${RELEASE_NAMESPACE}" \
                    --allow-ns "${RELEASE_NAMESPACE}" \
                    --app "${RELEASE_NAME}-${APP_NAME}" \
                    --diff-changes \
                    -f ./manifests/