---
apiVersion: verify.gov.uk/v1beta1
kind: CertificateRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: proxy-node-metadata-production-ca-a1
  namespace: verify-eidas-proxy-node-deploy
spec:
  countryCode: GB
  commonName: Proxy Node Metadata CA
  expiryMonths: 120
  organization: Cabinet Office
  organizationUnit: GDS
  location: London
  CACert: true
  certificateAuthority:
    secretName: verify-root-ca-production-a1
    namespace: verify-metadata-controller

