apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-notification
  namespace: verify-eidas-proxy-node-deploy
spec:
  encryptedData:
    url: AgCoLlO1XcJVZRwkYECUBSot75GSru8mNsEHpVpw/GjHVa9AUIPM5YJwM6hzP3Y1oLQ6Xata5jdE/HVw41JR7kgddYUpgtc6sAhjiq2luZWY8vshihW3cZUJCQSW/T9S9tVv2BbPhozvTqosMltwmiNP42cNb2LLGS9Tw/3pnPZgPBNa/MU+gqTa5VHq1tYq7jjoae96BOkHzjyy1PXmXgxZdVQhv/C7+1n8lK51UZVfG4qq9hFwfLqZM7DSnYBGc+baNAoEiFE9o+CYtmS6cMHmMY+98N6V2EuLTfEX2PDp1QPh5hTCZ2GDJZbU0b5lYYNK8hb9zUkcdCOw0py5gMU0vAMc5V8mL8lq8AO9H/np78pyE/02wxcqddh8rIZs4GmgTLTmQ5DxlRDV5c0Kp18fEk+rlT0RG6jWM6umLgM+d3o4Ct7+8IVy1M1KY+6RUmWYMnO9FiNdW2o9gg3D720J45kLbua15VmRUksVpO4n7NUr3dgjaWD2wLdtCMPZZt5N9/PSW41s3HmoxPjeu1EJY1Nmtvs5BHc+duBz9a2s18dWjc5RqwFQjCAp1KXVOt58ojk50J9TqHfSiV8E6FCm7X3pPR+nLpsFHH2eHpFBE7X8gh41j7Wp4k3Q63EM8ybwxjxaGpzczK4rpAvGldaU2AqnUiYHInTAO/iiWrB7isAjGlE+RAOBNkgHXvZClm7IiDCq2Z10hTX6olTyDEaiBtwKgBEFXR8hvMRhPJXcM5Ms4ME6HP2cgDL+7FN/f9uid4UhIlBGD2XNCqeCW3+hrz1QyD/CtJkObMrDYG4=
